name       : haskell-hslua-module-text
version    : 0.1.2.1
release    : 1
source     :
    - https://hackage.haskell.org/package/hslua-module-text-0.1.2.1/hslua-module-text-0.1.2.1.tar.gz : aeb384f9743b76360f3779e44065fe297fb60f27519933f203b75bd8c2ba8e2d
license    : MIT
component  : programming.haskell
summary    : UTF-8 aware subset of Lua's string module.
description: |
    UTF-8 aware subset of Lua's string module.
builddeps  :
    - haskell-cabal-install
    - haskell-fail
    - haskell-hslua
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
