name       : haskell-hslua-module-text
version    : 0.2.1
release    : 3
source     :
    - https://hackage.haskell.org/package/hslua-module-text-0.2.1/hslua-module-text-0.2.1.tar.gz : 1302d9022e9beea0cf4f09f977d7ca0956c598d0bf15945de5a52dd8f7e66dc6
license    : MIT
component  : programming.haskell
summary    : UTF-8 aware subset of Lua's string module.
description: |
    UTF-8 aware subset of Lua's string module.
builddeps  :
    - haskell-cabal-install
    - haskell-hslua-devel
rundeps    :
    - devel:
        - haskell-hslua-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
